
#apiVersion: v1
#kind: Pod
#metadata:
#  name: microservicio
#spec:
#  containers:
#    - name: hola-mundo
#      image: hoverdev/hola-mundo:4
#      ports:
#        - containerPort: 3000
#Deployment maneja pods y replica sets
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: microservicio
  labels:
    app: microservicio
    areanegocio: pagos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: hola-mundo
          image: susanar1/hola-mundo2:3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: microservicio
            - secretRef:
                name: microservicio
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
spec:
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicio
data:
  LOG_LEVEL: debug
---
apiVersion: v1
kind: Secret
metadata:
  name: microservicio
data:
  DATABASE_PASSWORD: U3VwZXJTZWd1cm8yMDI1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservicio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization ## EN BASE AL REQUEST
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization ## EN BASE AL REQUEST
          averageUtilization: 90

            